services:
    rabbitmq:
      image: "rabbitmq:3.9.13-management-alpine"
      restart: always
      ports:
        - "15672:15672"
        - "5673:5672"
      volumes:
        - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
      environment:
        - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
        - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
    mongodb:
      image: mongo:latest
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - "./.mongodb_data:/data/db"
    postgres: 
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment: 
        - "POSTGRES_USER=${POSTGRES_USER}"
        - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        - "POSTGRES_DB=${POSTGRES_DB}"
      volumes:
        - ./data/postgres:/data/postgres