services:
    rabbitmq:
      image: "rabbitmq:3.9.13-management-alpine"
      restart: always
      ports:
        - "15672:15672"
        - "5672:5672"
      environment:
        - "RABBITMQ_DEFAULT_USER=root"
        - "RABBITMQ_DEFAULT_PASS=root"
    mongodb:
      image: mongo:latest
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - "./.mongodb_data:/data/db"
    postgres: 
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment: 
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=docker
      volumes:
        - ./data/postgres:/data/postgres