services:
    rabbitmq:
      image: "rabbitmq:3.9-management-alpine"
      hostname: rabbitmq
      restart: always
      ports:
        - "15672:15672"
        - "5673:5672"
      volumes:
        - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
      environment:
        - RABBITMQ_DEFAULT_USER=root
        - RABBITMQ_DEFAULT_PASS=root
    mongodb:
      image: mongo:latest
      restart: always
      ports:
        - "27017:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
      volumes:
        - "./.mongodb_data:/data/db"
    postgres: 
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment: 
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=docker
      volumes:
        - ./data/postgres:/data/postgres